services:
  springboot1:
    image: fiipractic_springboot:1.0
    container_name: springboot1
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1"
    environment:
      MY_VAR: springboot1

  springboot2:
    image: fiipractic_springboot:2.0
    container_name: springboot2
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1"
    environment:
      MY_VAR: springboot2

  nginx:
    image: nginx
    container_name: nginx
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "1"
    ports:
      - "8443:443"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx/index.html:/var/www/example/index.html
      - ./Nginx/app.crt:/usr/share/easy-rsa/3/pki/issued/app.crt
      - ./Nginx/app.key:/usr/share/easy-rsa/3/pki/private/app.key
    depends_on:
      - springboot1
      - springboot2